docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - "API overview": api.md
        - "Usage Scenarios": usage.md
        - Tools: tools.md
        - "Object-oriented access to the LDAP tree": node.md
        - "Getting information from the LDAP server": server.md
        - "Serializing LDAP data to and from LDIF": ldif.md
site_name: laminas-ldap
site_description: laminas-ldap
repo_url: 'https://github.com/laminas/laminas-ldap'
